### ISSUE TITLE
command line utility does not work with v0.8.0

### ISSUE THREAD

**Issue by o-sapov** [cemfi/meico#20]
I'm getting:
```
Started: java -jar "meicoPATH\meico.jar"  --wav -t 100  filePATH\dmeref_499-003_5859.xml
meico v0.8.0
Process ended with exit code: 0
```

- the code above is from oXygen notification panel, but the same issue prompts when using the command line
- until the v0.7.10 everything worked fine with the same command
- `meicoApp.jar ` can be run from the command line
Maybe I missed some changes in the usage?

**Comment by axelberndt** [comment]
Hi Oleksii,

from version 0.8.0 on you are supposed to use `meicoApp.jar` instead of `meico.jar`. The latter contains no application code anymore. It contains only the core functionality of meico that is needed for application development. It doesn't make sense to blow up the library three times its size with code that other applications will not need.

Ah, and I see that the corresponding documentation in `README.md` needs an according update. ... Done it.
